name: main

on:
  push:
    branches: [ main ]

env:
  SEMVERBOT_VERSION: "1.3.1"

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up path
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: install semverbot
        run: |
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x bin/sbot

      - name: update version
        run: |
          sbot update version --verbose

      - name: release version
        run: |
          sbot release version --verbose
          sbot push version --verbose
